
package ProgramasME;

import PKCASM.Faciles;

/**
 *
 * @author Camilo Sol
 */
public class TrianguloINTERFAZ extends javax.swing.JFrame {

    /**
     *
     */
    public Triangulos ca;

  
    public TrianguloINTERFAZ() {
        initComponents();
          this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PERFIL = new javax.swing.JLabel();
        INICIO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        INICIALES = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ANGULO2 = new javax.swing.JTextField();
        ANGULO1 = new javax.swing.JTextField();
        ANGULO3 = new javax.swing.JTextField();
        RESULTADO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        EMERGE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PERFIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PERFIL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_PERFIL/PERFIL1.png"))); // NOI18N
        getContentPane().add(PERFIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 250, 250));

        INICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INICIOMouseClicked(evt);
            }
        });
        getContentPane().add(INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Volver");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 62, 27));

        INICIALES.setBackground(new java.awt.Color(240, 240, 245));
        INICIALES.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        INICIALES.setForeground(new java.awt.Color(255, 255, 255));
        INICIALES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIALES.setText("CASM");
        getContentPane().add(INICIALES, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 140, -1));

        titulo.setBackground(new java.awt.Color(240, 240, 245));
        titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Camilo Abel Sol Mosquera");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 220, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TERSER ANGULO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEGUNDO ANGULO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRIMER ANGULO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, 30));

        ANGULO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGULO2ActionPerformed(evt);
            }
        });
        getContentPane().add(ANGULO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 180, 40));

        ANGULO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGULO1ActionPerformed(evt);
            }
        });
        getContentPane().add(ANGULO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 180, 40));

        ANGULO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGULO3ActionPerformed(evt);
            }
        });
        getContentPane().add(ANGULO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 180, 40));

        RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 180, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TIPO DE ANGULO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 120, 30));

        calcular.setText("DEFINIR");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 80, 30));

        EMERGE.setText("DEFINIR EN VENTANA EMERGENTE");
        EMERGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMERGEActionPerformed(evt);
            }
        });
        getContentPane().add(EMERGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 35.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Faciles CA = new Faciles ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void INICIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INICIOMouseClicked
   
    }//GEN-LAST:event_INICIOMouseClicked

    private void RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESULTADOActionPerformed

    private void ANGULO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGULO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANGULO2ActionPerformed

    private void ANGULO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGULO1ActionPerformed
      
    }//GEN-LAST:event_ANGULO1ActionPerformed

    private void ANGULO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGULO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANGULO3ActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
           
     String sx=ANGULO1.getText();
    double x = Double.parseDouble(sx);
    String sy=ANGULO2.getText();
    double y = Double.parseDouble(sy);
    String sz=ANGULO3.getText();
    double z = Double.parseDouble(sz);
       ca=new Triangulos();
        String r = ca.DeterminarTipoTriangulo();
    RESULTADO.setText(r+"");
 
    }//GEN-LAST:event_calcularActionPerformed

    private void EMERGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMERGEActionPerformed
      Triangulos pa = new Triangulos ();
      pa.PedirLadosTriangulos();
      pa.DeterminarTipoTriangulo();
      pa.MostrarTipoTriangulo();
    }//GEN-LAST:event_EMERGEActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrianguloINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrianguloINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrianguloINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrianguloINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TrianguloINTERFAZ().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANGULO1;
    private javax.swing.JTextField ANGULO2;
    private javax.swing.JTextField ANGULO3;
    private javax.swing.JButton EMERGE;
    private javax.swing.JLabel INICIALES;
    private javax.swing.JLabel INICIO;
    private javax.swing.JLabel PERFIL;
    private javax.swing.JTextField RESULTADO;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
