/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PKCASM;
import java.awt.Color;
import ProgramasME.TrianguloINTERFAZ;

/**
 *
 * @author Camilo Sol
 */
public class Medios extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Medios() {
        initComponents();
         this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitBotom = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ExitBotom1 = new javax.swing.JLabel();
        FOTO = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        INICIALES = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBotom.setBackground(new java.awt.Color(0, 0, 0));
        ExitBotom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBotom.setText("X");
        ExitBotom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBotom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBotomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBotomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBotomMouseExited(evt);
            }
        });
        jPanel1.add(ExitBotom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 33, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 151, 175));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBotom1.setBackground(new java.awt.Color(0, 0, 0));
        ExitBotom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBotom1.setText("X");
        ExitBotom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBotom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseExited(evt);
            }
        });
        jPanel2.add(ExitBotom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 33, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 20));

        FOTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_PERFIL/PERFIL 19.jpg"))); // NOI18N
        getContentPane().add(FOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 240, 210));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTRAR");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 70, 30));

        INICIALES.setBackground(new java.awt.Color(240, 240, 245));
        INICIALES.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        INICIALES.setForeground(new java.awt.Color(255, 255, 255));
        INICIALES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIALES.setText("CASM");
        INICIALES.setToolTipText("autor");
        getContentPane().add(INICIALES, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 50, 30));

        titulo.setBackground(new java.awt.Color(240, 240, 245));
        titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Camilo Abel Sol Mosquera");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 220, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Volver");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 68, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROGRAMAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo De Triangulo");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 30.jpg"))); // NOI18N
        BG.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        VentanaPRINCASM CA = new VentanaPRINCASM ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TrianguloINTERFAZ CA = new TrianguloINTERFAZ ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void ExitBotomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotomMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBotomMouseClicked

    private void ExitBotomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotomMouseEntered
        ExitBotom.setBackground(Color.red);
        ExitBotom.setForeground(Color.white);

    }//GEN-LAST:event_ExitBotomMouseEntered

    private void ExitBotomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotomMouseExited
        ExitBotom.setBackground(Color.white);
        ExitBotom.setForeground(Color.black);
    }//GEN-LAST:event_ExitBotomMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse= evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void ExitBotom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBotom1MouseClicked

    private void ExitBotom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseEntered
        ExitBotom.setBackground(Color.red);
        ExitBotom.setForeground(Color.white);

    }//GEN-LAST:event_ExitBotom1MouseEntered

    private void ExitBotom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseExited
        ExitBotom.setBackground(Color.white);
        ExitBotom.setForeground(Color.black);
    }//GEN-LAST:event_ExitBotom1MouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse= evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel ExitBotom;
    private javax.swing.JLabel ExitBotom1;
    private javax.swing.JLabel FOTO;
    private javax.swing.JLabel INICIALES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
