/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramasFA;

import java.awt.Color;

/**
 *
 * @author Camilo Sol
 */
public class calculadoraINTERFAZ extends javax.swing.JFrame {

    /**
     * Creates new form calculadoraINTERFAZ
     */
    public calculadoraINTERFAZ() {
        initComponents();
        Calculadora ca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CALCULAR = new javax.swing.JButton();
        DIVIDIR = new javax.swing.JButton();
        MULTIPLICAR = new javax.swing.JButton();
        RESTAR = new javax.swing.JButton();
        SUMAR = new javax.swing.JButton();
        NUMERO2 = new javax.swing.JTextField();
        NUMERO1 = new javax.swing.JTextField();
        RESULTADO1 = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 146, 57));

        DIVIDIR.setText("DIVIDIR");
        DIVIDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVIDIRActionPerformed(evt);
            }
        });
        getContentPane().add(DIVIDIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        MULTIPLICAR.setText("MULTIPLICAR");
        MULTIPLICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLICARActionPerformed(evt);
            }
        });
        getContentPane().add(MULTIPLICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        RESTAR.setText("RESTAR");
        RESTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTARActionPerformed(evt);
            }
        });
        getContentPane().add(RESTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        SUMAR.setText("SUMAR");
        SUMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMARActionPerformed(evt);
            }
        });
        getContentPane().add(SUMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        NUMERO2.setForeground(new java.awt.Color(153, 153, 153));
        NUMERO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NUMERO2.setText("INGRESE NUMERO");
        NUMERO2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUMERO2MousePressed(evt);
            }
        });
        getContentPane().add(NUMERO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, 50));

        NUMERO1.setForeground(new java.awt.Color(153, 153, 153));
        NUMERO1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NUMERO1.setText("INGRESE NUMERO");
        NUMERO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUMERO1MousePressed(evt);
            }
        });
        NUMERO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMERO1ActionPerformed(evt);
            }
        });
        getContentPane().add(NUMERO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, 50));

        RESULTADO1.setEditable(false);
        RESULTADO1.setForeground(new java.awt.Color(153, 153, 153));
        RESULTADO1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RESULTADO1.setText("RESULTADO");
        RESULTADO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RESULTADO1MousePressed(evt);
            }
        });
        getContentPane().add(RESULTADO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 200, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 8.jpg"))); // NOI18N
        BG.setToolTipText("");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMARActionPerformed
    Calculadora ca=new Calculadora ();
     String sx=NUMERO1.getText();
    double x = Double.parseDouble(sx);
    String sy=NUMERO2.getText();
    double y = Double.parseDouble(sy);
      ca=new Calculadora(x,y);
    double r = ca.sumar();
    RESULTADO1.setText(r + "");
    }//GEN-LAST:event_SUMARActionPerformed

    private void NUMERO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMERO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMERO1ActionPerformed

    private void RESTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTARActionPerformed
      Calculadora ca=new Calculadora ();
     String sx=NUMERO1.getText();
    double x = Double.parseDouble(sx);
    String sy=NUMERO2.getText();
    double y = Double.parseDouble(sy);
      ca=new Calculadora(x,y);
    double r = ca.restar();
    RESULTADO1.setText(r + "");
    }//GEN-LAST:event_RESTARActionPerformed

    private void MULTIPLICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLICARActionPerformed
       Calculadora ca=new Calculadora ();
     String sx=NUMERO1.getText();
    double x = Double.parseDouble(sx);
    String sy=NUMERO2.getText();
    double y = Double.parseDouble(sy);
      ca=new Calculadora(x,y);
    double r = ca.multiplicar();
    RESULTADO1.setText(r + "");
    }//GEN-LAST:event_MULTIPLICARActionPerformed

    private void DIVIDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVIDIRActionPerformed
           Calculadora ca=new Calculadora ();
     String sx=NUMERO1.getText();
    double x = Double.parseDouble(sx);
    String sy=NUMERO2.getText();
    double y = Double.parseDouble(sy);
      ca=new Calculadora(x,y);
    double r = ca.dividir();
    RESULTADO1.setText(r + "");
    }//GEN-LAST:event_DIVIDIRActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CALCULARActionPerformed

    private void NUMERO1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUMERO1MousePressed

    }//GEN-LAST:event_NUMERO1MousePressed

    private void NUMERO2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUMERO2MousePressed
   
    }//GEN-LAST:event_NUMERO2MousePressed

    private void RESULTADO1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESULTADO1MousePressed
        NUMERO1.setForeground(Color.black);
     NUMERO2.setText("");
     NUMERO1.setForeground(Color.gray);
    }//GEN-LAST:event_RESULTADO1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoraINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoraINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoraINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoraINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoraINTERFAZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JButton DIVIDIR;
    private javax.swing.JButton MULTIPLICAR;
    private javax.swing.JTextField NUMERO1;
    private javax.swing.JTextField NUMERO2;
    private javax.swing.JButton RESTAR;
    private javax.swing.JTextField RESULTADO1;
    private javax.swing.JButton SUMAR;
    // End of variables declaration//GEN-END:variables
}
