
package ProgramasFA;

import PKCASM.Faciles;
import java.awt.Color;

/**
 *
 * @author Camilo Sol
 */
public class HOLAMUNDOINTERFAZ extends javax.swing.JFrame {

     int xMouse, yMouse;
    public HOLAMUNDOINTERFAZ() {
        initComponents();
        this.setLocationRelativeTo(this);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        INICIALES = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        PERFIL1 = new javax.swing.JLabel();
        SALIDA = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ventana = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        emergente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ExitBotom1 = new javax.swing.JLabel();
        PERFIL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        INICIALES1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Volver");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        INICIALES.setBackground(new java.awt.Color(240, 240, 245));
        INICIALES.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        INICIALES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIALES.setText("CASM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(240, 240, 245));
        titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Camilo Abel Sol Mosquera");
        titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 15.jpg")))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 210, 30));

        PERFIL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PERFIL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_PERFIL/perfil2.png"))); // NOI18N
        getContentPane().add(PERFIL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 120, 90));

        SALIDA.setEditable(false);
        SALIDA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SALIDA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SALIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIDAActionPerformed(evt);
            }
        });
        getContentPane().add(SALIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 280, 100));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIMPIAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 70, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        ventana.setBackground(new java.awt.Color(204, 204, 255));
        ventana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ventana.setForeground(new java.awt.Color(255, 255, 255));
        ventana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventana.setText("Mensaje por ventana");
        ventana.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        ventana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ventana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventanaMouseClicked(evt);
            }
        });
        jPanel3.add(ventana);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 220, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        emergente.setBackground(new java.awt.Color(204, 204, 255));
        emergente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emergente.setForeground(new java.awt.Color(255, 255, 255));
        emergente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergente.setText("Mensaje por ventana emergente");
        emergente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emergente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emergenteMouseClicked(evt);
            }
        });
        jPanel1.add(emergente);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 270, 40));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBotom1.setBackground(new java.awt.Color(0, 0, 0));
        ExitBotom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBotom1.setText("X");
        ExitBotom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBotom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBotom1MouseExited(evt);
            }
        });
        jPanel2.add(ExitBotom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 33, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 20));

        PERFIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PERFIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 13, 170, 150));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Volver");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 60, 20));

        INICIALES1.setBackground(new java.awt.Color(240, 240, 245));
        INICIALES1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        INICIALES1.setForeground(new java.awt.Color(255, 255, 255));
        INICIALES1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIALES1.setText("CASM");
        INICIALES1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(INICIALES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 9.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 950, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Faciles CA = new Faciles ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Faciles CA = new Faciles ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ventanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventanaMouseClicked
    SALIDA.setText("¡¡Hola mundo!!");
    }//GEN-LAST:event_ventanaMouseClicked

    private void emergenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergenteMouseClicked
       HOLAMUNDO sa = new HOLAMUNDO ();
       sa.saludar();
    }//GEN-LAST:event_emergenteMouseClicked

    private void ExitBotom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBotom1MouseClicked

    private void ExitBotom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseEntered
        ExitBotom1.setBackground(Color.red);
        ExitBotom1.setForeground(Color.white);
    }//GEN-LAST:event_ExitBotom1MouseEntered

    private void ExitBotom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom1MouseExited
        ExitBotom1.setBackground(Color.white);
        ExitBotom1.setForeground(Color.black);
    }//GEN-LAST:event_ExitBotom1MouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse= evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void SALIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALIDAActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       Borrar();
    }//GEN-LAST:event_jLabel4MouseClicked
 private void Borrar() {
    SALIDA.setText("");
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOLAMUNDOINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOLAMUNDOINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOLAMUNDOINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOLAMUNDOINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOLAMUNDOINTERFAZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBotom1;
    private javax.swing.JLabel INICIALES;
    private javax.swing.JLabel INICIALES1;
    private javax.swing.JLabel PERFIL;
    private javax.swing.JLabel PERFIL1;
    private javax.swing.JTextField SALIDA;
    private javax.swing.JLabel emergente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel ventana;
    // End of variables declaration//GEN-END:variables
}
