/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramasFA;

import PKCASM.ES;
import PKCASM.Faciles;
import java.awt.Color;

/**
 *
 * @author Camilo Sol
 */
public class ImprimirPINTERFAZ extends javax.swing.JFrame {
    
ImprimirPares PO;
     int xMouse, yMouse;
    public ImprimirPINTERFAZ() {
        initComponents();
        this.setLocationRelativeTo(this);
         rsscalelabel.RSScaleLabel.setScaleLabel(PERFIL, "src/IMG_PERFIL/PERFIL 7.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ExitBotom2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        RESULTADO = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        NUMERO = new javax.swing.JLabel();
        PERFIL = new javax.swing.JLabel();
        INICIALES = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Volver");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 60, 30));

        jPanel4.setBackground(new java.awt.Color(20, 98, 120));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBotom2.setBackground(new java.awt.Color(0, 0, 0));
        ExitBotom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBotom2.setText("X");
        ExitBotom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBotom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBotom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBotom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBotom2MouseExited(evt);
            }
        });
        jPanel4.add(ExitBotom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 33, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 20));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("IMPRIMIR POR VENTANA EMERGENTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jButton1.setText("IMPRIMIR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 280, 120));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 270, 30));

        NUMERO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NUMERO.setForeground(new java.awt.Color(255, 255, 255));
        NUMERO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUMERO.setText("DIGITE NUMERO");
        NUMERO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUMEROMouseClicked(evt);
            }
        });
        getContentPane().add(NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 50));

        PERFIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PERFIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 210, 200));

        INICIALES.setBackground(new java.awt.Color(240, 240, 245));
        INICIALES.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        INICIALES.setForeground(new java.awt.Color(255, 255, 255));
        INICIALES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INICIALES.setText("CASM");
        getContentPane().add(INICIALES, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, -1, 30));

        titulo.setBackground(new java.awt.Color(240, 240, 245));
        titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Camilo Abel Sol Mosquera");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 220, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO 25.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Faciles CA = new Faciles ();
        CA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void NUMEROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUMEROMouseClicked
   
    }//GEN-LAST:event_NUMEROMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
ImprimirPares ca=new ImprimirPares ();
     String sx=NUMERO.getText();
    double x = Double.parseDouble(sx);     
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESULTADOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitBotom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBotom2MouseClicked

    private void ExitBotom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom2MouseEntered
        ExitBotom2.setBackground(Color.red);
        ExitBotom2.setForeground(Color.white);
    }//GEN-LAST:event_ExitBotom2MouseEntered

    private void ExitBotom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBotom2MouseExited
        ExitBotom2.setBackground(Color.white);
        ExitBotom2.setForeground(Color.black);
    }//GEN-LAST:event_ExitBotom2MouseExited

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse= evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ImprimirPares pa = new ImprimirPares ();
       pa.Pares();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//      String sx=NUMERO.getText();
//    double x = Double.parseDouble(sx);
//    String sy=RESULTADO.getText();
//       PO=new ImprimirPares();
//        String r = PO.toString();
//    RESULTADO.setText(r+"");
 
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirPINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirPINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirPINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirPINTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImprimirPINTERFAZ().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBotom2;
    private javax.swing.JLabel INICIALES;
    private javax.swing.JLabel NUMERO;
    private javax.swing.JLabel PERFIL;
    private javax.swing.JTextField RESULTADO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
